# Generated by Django 5.1.2 on 2025-03-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cook_time2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
