# Generated by Django 5.1.2 on 2025-03-28 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_cook_time2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='cook_time2',
        ),
    ]
