# Generated by Django 5.2 on 2025-05-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_recipeingredient_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailcategory',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='detailcategory',
            unique_together={('name', 'category')},
        ),
    ]
